title: 'Tutorial 1 Teaching Solutions: Business Analytics Skills for Inventory Management'
author: Foundations of Business Analytics
date: today
date-format: "MMMM, YYYY"
project:
  render:
    - tutorial.qmd
format:
  html:
    output-file: "tutorial-01-solutions"
    output-ext:  "html"
